#pragma checksum "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "02A0181509CE29EA350A4555D779CAEA54D7934200F90B24414D7D601B3814F4"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using EyeSave_Demo.Pages.AddEditPages;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace EyeSave_Demo.Pages.AddEditPages {
    
    
    /// <summary>
    /// AddEditAgentPage
    /// </summary>
    public partial class AddEditAgentPage : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TitleTb;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AgentTypeCb;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PriorityTb;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddressTb;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox INNTb;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox KPPTb;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DirNameTb;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PhoneTb;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmailTb;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image LogoImg;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveImageBtn;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid HistorySalesDg;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddSalesBtn;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeleteSalesBtn;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveAgentBtn;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeleteAgentBtn;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/EyeSave_Demo;component/pages/addeditpages/addeditagentpage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TitleTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 15 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.TitleTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TitleTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 2:
            this.AgentTypeCb = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.PriorityTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 19 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.PriorityTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.PriorityTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 4:
            this.AddressTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 21 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.AddressTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.AddressTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 5:
            this.INNTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 23 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.INNTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.INNTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 6:
            this.KPPTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 25 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.KPPTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.KPPTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 7:
            this.DirNameTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 27 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.DirNameTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.DirNameTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 8:
            this.PhoneTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 29 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.PhoneTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.PhoneTb_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 9:
            this.EmailTb = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.LogoImg = ((System.Windows.Controls.Image)(target));
            return;
            case 11:
            this.SaveImageBtn = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.SaveImageBtn.Click += new System.Windows.RoutedEventHandler(this.SaveImageBtn_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.HistorySalesDg = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 13:
            this.AddSalesBtn = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.AddSalesBtn.Click += new System.Windows.RoutedEventHandler(this.AddSalesBtn_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.DeleteSalesBtn = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.DeleteSalesBtn.Click += new System.Windows.RoutedEventHandler(this.DeleteSalesBtn_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.SaveAgentBtn = ((System.Windows.Controls.Button)(target));
            
            #line 55 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.SaveAgentBtn.Click += new System.Windows.RoutedEventHandler(this.SaveAgentBtn_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.DeleteAgentBtn = ((System.Windows.Controls.Button)(target));
            
            #line 56 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.DeleteAgentBtn.Click += new System.Windows.RoutedEventHandler(this.DeleteAgentBtn_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BackBtn = ((System.Windows.Controls.Button)(target));
            
            #line 57 "..\..\..\..\Pages\AddEditPages\AddEditAgentPage.xaml"
            this.BackBtn.Click += new System.Windows.RoutedEventHandler(this.BackBtn_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

