#pragma checksum "..\..\..\..\Pages\DataPages\AgentsPage.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1373B3C68F58CBCA58C92F115EEAC68CCDF6E363FB114C573D1D44DF6C148B9F"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using EyeSave_Demo.Pages.DataPages;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace EyeSave_Demo.Pages.DataPages {
    
    
    /// <summary>
    /// AgentsPage
    /// </summary>
    public partial class AgentsPage : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 13 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddAgentBtn;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchTb;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FilterCb;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AgentTypeCb;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView AgentsList;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ChangePriorityBtn;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackBtn;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel NavButtonsSt;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NextBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/EyeSave_Demo;component/pages/datapages/agentspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.AddAgentBtn = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.AddAgentBtn.Click += new System.Windows.RoutedEventHandler(this.AddAgentBtn_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SearchTb = ((System.Windows.Controls.TextBox)(target));
            
            #line 17 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.SearchTb.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.SearchTb_PreviewTextInput);
            
            #line default
            #line hidden
            
            #line 17 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.SearchTb.GotKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.SearchTb_GotKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 17 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.SearchTb.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.SearchTb_LostKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 3:
            this.FilterCb = ((System.Windows.Controls.ComboBox)(target));
            
            #line 18 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.FilterCb.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.FilterCb_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.AgentTypeCb = ((System.Windows.Controls.ComboBox)(target));
            
            #line 26 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.AgentTypeCb.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.AgentTypeCb_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.AgentsList = ((System.Windows.Controls.ListView)(target));
            
            #line 29 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.AgentsList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.AgentsList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ChangePriorityBtn = ((System.Windows.Controls.Button)(target));
            
            #line 55 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.ChangePriorityBtn.Click += new System.Windows.RoutedEventHandler(this.ChangePriorityBtn_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BackBtn = ((System.Windows.Controls.Button)(target));
            
            #line 58 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.BackBtn.Click += new System.Windows.RoutedEventHandler(this.BackBtn_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.NavButtonsSt = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 10:
            this.NextBtn = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            this.NextBtn.Click += new System.Windows.RoutedEventHandler(this.NextBtn_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 6:
            
            #line 32 "..\..\..\..\Pages\DataPages\AgentsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Border_MouseDown);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

